apiVersion: apps/v1
kind: Deployment
metadata:
  name: user
  labels:
    app: user
spec:
  replicas: 1
  template:
    metadata:
      name: user
      labels:
        app: user
    spec:
      containers:
        - name: payment
          image: vishnuganb/user:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 6001
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: kube
      restartPolicy: Always
  selector:
    matchLabels:
      app: user
