version: '3'

services:

  mysql:
    container_name: mysql
    image: mysql:8.0
    environment:
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD:
    volumes:
      - my-db:/var/lib/mysql
    ports:
      - "4500:4500"
    networks:
      - mysql
    restart: unless-stopped

  user:
    container_name: user
    image: ubuntu:20.04  # Replace with the name and tag of the image you want to use
    ports:
      - "6001:6001"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - spring
      - mysql
    depends_on:
      - mysql

networks:
  mysql:
    driver: bridge
  spring:
    driver: bridge

volumes:
  my-db: