apiVersion: apps/v1
kind: Deployment
metadata:
  name: item
  labels:
    app: item
spec:
  replicas: 1
  template:
    metadata:
      name: item
      labels:
        app: item
    spec:
      containers:
        - name: item
          image: dhanushka117/item:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 6002
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: kube
      restartPolicy: Always
  selector:
    matchLabels:
      app: item
