apiVersion: apps/v1
kind: Deployment
metadata:
  name: email
  labels:
    app: email
spec:
  replicas: 1
  template:
    metadata:
      name: email
      labels:
        app: email
    spec:
      containers:
        - name: email
          image: vishnuganb/email:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 7001
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: kube
      restartPolicy: Always
  selector:
    matchLabels:
      app: email
