server:
  port: 8003
  servlet:
    session:
      persistent: false

spring:
  application:
    name: user
  datasource:
    url: jdbc:mysql://localhost:3306/user_db
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    open-in-view: false
  mail:
    host: smtp.gmail.com
    port: 587
    username: donateus.global@gmail.com
    password: hjnsumbfaiezqtrm
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka