server:
  port: 6001
  servlet:
    session:
      persistent: false

spring:
  application:
    name:
      user
  datasource:
    url: jdbc:mysql://mysql:3306/user_db
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop # when kubernetes service>replicas is more than 1, make this as update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    show-sql: true
    open-in-view: false
